server:
  port: 8090
spring:
  application:
    name: GATWAY
  cloud:
    consul:
      host: 112.74.186.85
      port=8500:
      discovery:
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: category_router  # 路由对象唯一标识
          #uri: http://localhost:8086  # category 服务地址http://localhost:8086/category
          uri: lb://CATEGORY
          predicates: # 断言  配置路由规则
            - Path=/category

        - id: product_router  # 路由对象唯一标识
          #uri: http://localhost:8087  # category 服务地址 http://localhost:8087/product
          uri: lb://PRODUCT
          predicates: # 断言  配置路由规则
            - Path=/product
            #- Cookie=name,tnt  #携带指定 Cookie 才可用

          filters:
            - AddRequestParameter=color,blue
management:
  endpoints:
    web:
      exposure:
        include: "*"
